### ISSUE TITLE
stable baselines package not available. 

### ISSUE THREAD

**Issue by akjagadish** [sreejank/Compositional_MetaRL#1]
Hi Sreejan, 

I was trying to play around with your task and train your meta-RL agent. I found that one of your dependencies `stable_baselines` is not available. I presume it is an internal repository of the lab. Can you please make the relevant methods/classes available?

**Comment by sreejank** [comment]
Hi Akshay,

Thanks for your interest. stable_baselines is actually an open source package (https://stable-baselines.readthedocs.io/en/master/index.html). I have added a requirements.txt to the repo so you can see a list of dependencies you will need.
